### ISSUE TITLE
[TODO LIST] 博客待办事项

### ISSUE THREAD

**Issue by JoyWonderful** [JoyWonderful/blog-generation-files#1]
## 增加功能（特性、文章）
- [x] [增加置顶功能](https://github.com/JoyWonderful/joywonderful.github.io/issues/1#issuecomment-1600613971)
- [x] 增加友情链接
- [x] [增加 `RSS` 订阅](https://github.com/JoyWonderful/joywonderful.github.io/issues/1#issuecomment-1598009640)
## 进行更改美化
- [x] 优化“更多”页面（太丑了）
- [x] [修改相册，有Bug](https://github.com/JoyWonderful/joywonderful.github.io/issues/1#issuecomment-1651171488)
- [x] 把搜索按钮弹出页面进行更改美化

**Comment by JoyWonderful** [comment]
增加了 RSS 订阅源。

**Comment by JoyWonderful** [comment]
增加了置顶功能，但暂时没有置顶的文章。

**Comment by JoyWonderful** [comment]
置顶功能用上了，再一次更改了"更多页面"~~也许更丑了~~，同时增加了友情链接，分别是我老师和同学的。

**Comment by JoyWonderful** [comment]
昨天改好了类似于“相册”的页面（其实是改了原来 `/pic` 的页面。）
第一次 commit: https://github.com/JoyWonderful/joywonderful.github.io/commit/9a1b3d9aad0d7313ced4d335973ec82d9346fe1e
第二次更改好的 commit: https://github.com/JoyWonderful/joywonderful.github.io/commit/492ecea8360ee53ce5202599c5ea1d71c54a9f72

**Comment by JoyWonderful** [comment]
> 置顶功能用上了，再一次更改了"更多页面"~也许更丑了~，同时增加了友情链接，分别是我老师和同学的。

回：有没有文章置顶了。隐藏了几篇文章（好多天前）。

**Comment by JoyWonderful** [comment]
剩下的 task 还是删了吧，感觉没必要，什么时候加上一点。

**Comment by JoyWonderful** [comment]
准备修改相册  
注：CSS 中的 div 容器 `height` 不能直接设定(bug)，~~我太弱，不太会用 CSS~~，考虑使用 @next-theme 中提供的 "Tag Plugins" 中的 ["Group Pictures"](https://theme-next.js.org/docs/tag-plugins/group-pictures.html)

https://github.com/JoyWonderful/joywonderful.github.io/issues/1#issuecomment-1652899098

**Comment by JoyWonderful** [comment]
准备什么时候再菜单栏右侧加上淡淡的英文，如 "HOME" "CATEGORIES" 之类的，也许弄不好。

**Comment by JoyWonderful** [comment]
改好了，没用上 GroupPictures，加了个[屎山 JS](https://github.com/JoyWonderful/joywonderful.github.io/commit/c4d01fe4e0527725ca7d20ada27ddc054e256a82#diff-b1d455559b79881b7086176b33448b86af37652e7ec3e21630fa9047df2bc6f8R365)。可以任意更改大小 div 容器的高度也会缩放，不会出现一大片空白或图片紊乱的情况了~~吧~~。。。

https://github.com/JoyWonderful/joywonderful.github.io/blob/c4d01fe4e0527725ca7d20ada27ddc054e256a82/pic/index.html#L365-L387

**Comment by JoyWonderful** [comment]
要不菜单栏不改了

**Comment by JoyWonderful** [comment]
好像也没有什么要加上的了，那就关掉吧，什么时候有想法了再开一个 Issue，这个清单告一段落。

**Comment by JoyWonderful** [comment]
呃，search-popup 改了一下浮现的动画 `trasform`

**Comment by JoyWonderful** [comment]
最好在 github 里建立 wiki
